apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
    nginx.ingress.kubernetes.io/auth-url: "http://{{ .Values.global.domain }}:8000/accounts/auth/"
    nginx.ingress.kubernetes.io/auth-signin: "http://{{ .Values.global.domain }}:8000/accounts/login/"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  rules:
    - host: {{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            service:
              name: {{ .Release.Name }}-lab-svc
              port:
                number: 80
          pathType: ImplementationSpecific
